name: alleleflux-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - sphinx>=7.0.0
  - furo>=2024.1.0
  - myst-parser>=2.0.0
  - sphinx-copybutton>=0.5.0
  - sphinx-autobuild>=2021.3.14
  - sphinx-autodoc-typehints>=1.23.0
